# Generated by Django 2.2.1 on 2019-06-11 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190611_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=72),
            preserve_default=False,
        ),
    ]
