# Generated by Django 2.2.1 on 2019-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_class_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='note',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
