# Generated by Django 2.2.1 on 2019-08-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190612_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='note',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
