# Generated by Django 2.2.5 on 2019-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190828_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payed_period',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
