# Generated by Django 2.2.16 on 2020-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200211_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='paid_period',
            new_name='payment_current_period',
        ),
        migrations.AddField(
            model_name='member',
            name='payment_previous_period',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
